- hosts: namenode
  vars_prompt:
  - name: namenode_directory
    prompt: Enter the absolute directory path of namenode
    private: no
  tasks:
  - name: copying JDK rpm file
    copy:
      src: /root/jdk-8u171-linux-x64.rpm
      dest: /root/jdk-8u171-linux-x64.rpm
  - name: copying Hadoop rpm file
    copy:
      src: /root/hadoop-1.2.1-1.x86_64.rpm
      dest: /root/hadoop-1.2.1-1.x86_64.rpm
  - name: Checking java is installed or not
    command: java -version
    register: j
    ignore_errors: yes
  - name: Installing java
    command: rpm -i /root/jdk-8u171-linux-x64.rpm
    when: j.rc != 0
  - name: Checking hadoop is installed or not
    command: hadoop version
    register: h
    ignore_errors: yes
  - name: Installing hadoop
    command: rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force
    when: h.rc != 0
  - name: Creating namenode directory
    file:
      path: "{{ namenode_directory  }}"
      state: directory
  - name: Copying hdfs-site.xml file
    template:
      src: /root/hdfs-site.xml
      dest: /etc/hadoop/hdfs-site.xml
  - name: Copying core-site.xml file
    template:
      src: /root/core-site.xml
      dest: /etc/hadoop/core-site.xml
  - name: Enabling port 50070
    firewalld:
      port: 50070/tcp
      state: enabled
      permanent: yes
      immediate: yes
  - name: Enabling port 9001
    firewalld:
      port: 9001/tcp
      state: enabled
      permanent: yes
      immediate: yes
  - name: Checking namenode is running or not
    command: curl http://{{ groups['namenode'][0] }}:50070
    register: x
    failed_when: false
    ignore_errors: yes
  - name: Formatting namenode directory
    shell: echo  Y | hadoop namenode -format
    when: x.rc != 0
  - name: Starting namenode
    command: hadoop-daemon.sh start namenode
    when: x.rc != 0
